<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query'
import type { AdminDownload, AdminOverview, AdminPayment, AdminSubscription, AdminUser } from '~/types/api'

definePageMeta({ layout: 'dashboard' })
const auth = useAuthStore()
const api = useApi()
const enabled = computed(() => auth.isAuthenticated && auth.isAdmin)
const overview = useQuery({ queryKey: ['admin', 'overview'], queryFn: () => api<AdminOverview>('/admin/overview'), enabled })
const users = useQuery({ queryKey: ['admin', 'users'], queryFn: () => api<AdminUser[]>('/admin/users'), enabled })
const payments = useQuery({ queryKey: ['admin', 'payments'], queryFn: () => api<AdminPayment[]>('/admin/payments'), enabled })
const downloads = useQuery({ queryKey: ['admin', 'downloads'], queryFn: () => api<AdminDownload[]>('/admin/downloads'), enabled })
const subscriptions = useQuery({ queryKey: ['admin', 'subscriptions'], queryFn: () => api<AdminSubscription[]>('/admin/subscriptions'), enabled })
const metrics = computed(() => overview.data.value)
const busy = computed(() => [overview, users, payments, downloads, subscriptions].some((query) => query.isPending.value))
const failed = computed(() => [overview, users, payments, downloads, subscriptions].some((query) => query.isError.value))
const money = (amount: string, currency: string) => `${currency} ${Number(amount).toLocaleString(undefined, { minimumFractionDigits: 2 })}`
</script>

<template><div><PageTitle title="Admin overview" description="Monitor VidFixa accounts, subscriptions, payments, and downloads."/>
  <div v-if="busy" class="rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Loading admin data…</div>
  <div v-else-if="failed" class="rounded-2xl bg-red-50 p-5 text-sm text-red-700">Some admin data could not be loaded. Check the API connection and refresh.</div>
  <template v-else-if="metrics"><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><AdminMetric label="Total users" :value="metrics.total_users.toLocaleString()" detail="Registered accounts"/><AdminMetric label="Active subscriptions" :value="metrics.active_subscriptions.toLocaleString()" detail="Active paid access"/><AdminMetric label="Successful payments" :value="metrics.successful_payments.toLocaleString()" detail="Confirmed by provider webhook"/><AdminMetric label="Failed downloads" :value="metrics.failed_downloads.toLocaleString()" :detail="`${metrics.total_downloads.toLocaleString()} total downloads`"/></div>
    <section class="mt-9 grid gap-8 xl:grid-cols-2"><div><div class="mb-4 flex items-center justify-between"><h2 class="text-lg font-bold">Recent payments</h2><span class="text-xs text-slate-400">Read only · {{ payments.data.value?.length || 0 }} total</span></div><div class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div v-if="payments.data.value?.length" class="divide-y divide-slate-100"><div v-for="payment in payments.data.value.slice(0, 6)" :key="payment.id" class="flex items-center justify-between gap-3 px-4 py-3.5"><div class="min-w-0"><div class="truncate text-sm font-semibold">{{ payment.user_email }}</div><div class="mt-1 text-xs text-slate-500">{{ new Date(payment.created_at).toLocaleDateString() }} · {{ payment.provider_reference }}</div></div><div class="shrink-0 text-right"><div class="text-sm font-semibold">{{ money(payment.amount, payment.currency) }}</div><div class="mt-1"><StatusBadge :status="payment.status"/></div></div></div></div><div v-else class="p-8 text-center text-sm text-slate-500">No payment records yet.</div></div></div>
      <div><div class="mb-4 flex items-center justify-between"><h2 class="text-lg font-bold">Recent downloads</h2><span class="text-xs text-slate-400">{{ metrics.total_downloads.toLocaleString() }} total</span></div><div class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div v-if="downloads.data.value?.length" class="divide-y divide-slate-100"><div v-for="item in downloads.data.value.slice(0, 6)" :key="item.id" class="flex items-center justify-between gap-3 px-4 py-3.5"><div class="min-w-0"><div class="truncate text-sm font-semibold">{{ item.user_email || 'Anonymous visitor' }}</div><div class="mt-1 truncate text-xs text-slate-500">{{ item.platform }} · {{ new Date(item.created_at).toLocaleString() }}</div></div><StatusBadge :status="item.status"/></div></div><div v-else class="p-8 text-center text-sm text-slate-500">No downloads yet.</div></div></div></section>
    <section class="mt-9"><div class="mb-4 flex items-center justify-between"><h2 class="text-lg font-bold">Users</h2><span class="text-xs text-slate-400">{{ users.data.value?.length || 0 }} accounts</span></div><div class="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table class="w-full min-w-[540px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3 font-semibold">User</th><th class="px-4 py-3 font-semibold">Role</th><th class="px-4 py-3 font-semibold">Joined</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="user in users.data.value" :key="user.id"><td class="px-4 py-3"><div class="font-semibold">{{ user.full_name }}</div><div class="mt-0.5 text-xs text-slate-500">{{ user.email }}</div></td><td class="px-4 py-3 capitalize text-slate-600">{{ user.role }}</td><td class="px-4 py-3 text-slate-500">{{ new Date(user.created_at).toLocaleDateString() }}</td></tr><tr v-if="!users.data.value?.length"><td colspan="3" class="px-4 py-8 text-center text-slate-500">No user records yet.</td></tr></tbody></table></div></section>
    <section class="mt-9"><div class="mb-4 flex items-center justify-between"><h2 class="text-lg font-bold">Subscriptions</h2><span class="text-xs text-slate-400">Read only · {{ subscriptions.data.value?.length || 0 }} total</span></div><div class="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table class="w-full min-w-[620px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3 font-semibold">Account</th><th class="px-4 py-3 font-semibold">Plan</th><th class="px-4 py-3 font-semibold">Status</th><th class="px-4 py-3 font-semibold">Expires</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="subscription in subscriptions.data.value" :key="subscription.id"><td class="px-4 py-3 font-medium">{{ subscription.user_email }}</td><td class="px-4 py-3 capitalize">{{ subscription.plan }}</td><td class="px-4 py-3"><StatusBadge :status="subscription.status"/></td><td class="px-4 py-3 text-slate-500">{{ subscription.expires_at ? new Date(subscription.expires_at).toLocaleDateString() : '—' }}</td></tr><tr v-if="!subscriptions.data.value?.length"><td colspan="4" class="px-4 py-8 text-center text-slate-500">No subscriptions yet.</td></tr></tbody></table></div></section>
  </template>
</div></template>
